package com.sentinelpr.core.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.shreeai.os.platform.kernels.developer.codegen.model.PatchPlan;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * <b>CoordinatedPatchPlan</b>
 *
 * <p>Represents an atomic, coordinated multi-file remediation plan generated by SentinelPR,
 * wrapping both unified diff patches and the underlying Shree AI OS {@link PatchPlan}.</p>
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class CoordinatedPatchPlan {

    private final String planId;
    private final Instant createdAt;
    private final String intent;
    private final List<String> impactedFiles;
    private final List<UnifiedDiffPatch> filePatches;
    private final boolean verified;
    private final String verificationSummary;
    private final PatchPlan shreePatchPlan;

    @JsonCreator
    public CoordinatedPatchPlan(
            @JsonProperty("planId") String planId,
            @JsonProperty("createdAt") Instant createdAt,
            @JsonProperty("intent") String intent,
            @JsonProperty("impactedFiles") List<String> impactedFiles,
            @JsonProperty("filePatches") List<UnifiedDiffPatch> filePatches,
            @JsonProperty("verified") boolean verified,
            @JsonProperty("verificationSummary") String verificationSummary,
            @JsonProperty("shreePatchPlan") PatchPlan shreePatchPlan
    ) {
        this.planId = planId != null ? planId : "PLAN-" + UUID.randomUUID().toString().substring(0, 8);
        this.createdAt = createdAt != null ? createdAt : Instant.now();
        this.intent = intent != null ? intent : "Multi-file coordinated code refactoring";
        this.impactedFiles = impactedFiles != null
                ? Collections.unmodifiableList(new ArrayList<>(impactedFiles))
                : List.of();
        this.filePatches = filePatches != null
                ? Collections.unmodifiableList(new ArrayList<>(filePatches))
                : List.of();
        this.verified = verified;
        this.verificationSummary = verificationSummary != null ? verificationSummary : "";
        this.shreePatchPlan = shreePatchPlan;
    }

    public static Builder builder() {
        return new Builder();
    }

    public String getPlanId() {
        return planId;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public String getIntent() {
        return intent;
    }

    public List<String> getImpactedFiles() {
        return impactedFiles;
    }

    public List<UnifiedDiffPatch> getFilePatches() {
        return filePatches;
    }

    public boolean isVerified() {
        return verified;
    }

    public String getVerificationSummary() {
        return verificationSummary;
    }

    public PatchPlan getShreePatchPlan() {
        return shreePatchPlan;
    }

    public int getTotalTouchedFiles() {
        return impactedFiles.size();
    }

    @Override
    public String toString() {
        return "CoordinatedPatchPlan{" +
                "planId='" + planId + '\'' +
                ", intent='" + intent + '\'' +
                ", files=" + impactedFiles.size() +
                ", patches=" + filePatches.size() +
                ", verified=" + verified +
                '}';
    }

    public static class Builder {
        private String planId;
        private Instant createdAt = Instant.now();
        private String intent;
        private final List<String> impactedFiles = new ArrayList<>();
        private final List<UnifiedDiffPatch> filePatches = new ArrayList<>();
        private boolean verified = true;
        private String verificationSummary;
        private PatchPlan shreePatchPlan;

        public Builder planId(String planId) {
            this.planId = planId;
            return this;
        }

        public Builder intent(String intent) {
            this.intent = intent;
            return this;
        }

        public Builder addImpactedFile(String file) {
            if (file != null && !file.isBlank() && !impactedFiles.contains(file)) {
                this.impactedFiles.add(file);
            }
            return this;
        }

        public Builder addFilePatch(UnifiedDiffPatch patch) {
            if (patch != null) {
                this.filePatches.add(patch);
                addImpactedFile(patch.getTargetFile());
            }
            return this;
        }

        public Builder verified(boolean verified) {
            this.verified = verified;
            return this;
        }

        public Builder verificationSummary(String summary) {
            this.verificationSummary = summary;
            return this;
        }

        public Builder shreePatchPlan(PatchPlan plan) {
            this.shreePatchPlan = plan;
            return this;
        }

        public CoordinatedPatchPlan build() {
            return new CoordinatedPatchPlan(planId, createdAt, intent, impactedFiles, filePatches, verified, verificationSummary, shreePatchPlan);
        }
    }
}
