package com.sentinelpr.core.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.time.Instant;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * Structured enterprise audit report generated by SentinelPR.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ReviewReport {

    private final String reportId;
    private final Instant timestamp;
    private final String targetPath;
    private final int scannedFileCount;
    private final int vulnerabilityCount;
    private final String status;
    private final boolean cachedAudit;
    private final String summary;
    private final List<SecurityFinding> findings;
    private final List<SuppressedFinding> suppressedFindings;
    private final List<UnifiedDiffPatch> patches;

    public ReviewReport(
            String reportId,
            Instant timestamp,
            String targetPath,
            int scannedFileCount,
            int vulnerabilityCount,
            String status,
            boolean cachedAudit,
            String summary,
            List<SecurityFinding> findings,
            List<UnifiedDiffPatch> patches
    ) {
        this(reportId, timestamp, targetPath, scannedFileCount, vulnerabilityCount, status, cachedAudit, summary, findings, List.of(), patches);
    }

    public ReviewReport(
            String reportId,
            Instant timestamp,
            String targetPath,
            int scannedFileCount,
            int vulnerabilityCount,
            String status,
            boolean cachedAudit,
            String summary,
            List<SecurityFinding> findings,
            List<SuppressedFinding> suppressedFindings,
            List<UnifiedDiffPatch> patches
    ) {
        this.reportId = Objects.requireNonNull(reportId, "reportId must not be null");
        this.timestamp = timestamp != null ? timestamp : Instant.now();
        this.targetPath = targetPath != null ? targetPath : "";
        this.scannedFileCount = scannedFileCount;
        this.vulnerabilityCount = vulnerabilityCount;
        this.status = status != null ? status : "SUCCESS";
        this.cachedAudit = cachedAudit;
        this.summary = summary != null ? summary : "";
        this.findings = findings != null ? Collections.unmodifiableList(findings) : List.of();
        this.suppressedFindings = suppressedFindings != null ? Collections.unmodifiableList(suppressedFindings) : List.of();
        this.patches = patches != null ? Collections.unmodifiableList(patches) : List.of();
    }

    public String getReportId() {
        return reportId;
    }

    public Instant getTimestamp() {
        return timestamp;
    }

    public String getTargetPath() {
        return targetPath;
    }

    public int getScannedFileCount() {
        return scannedFileCount;
    }

    public int getVulnerabilityCount() {
        return vulnerabilityCount;
    }

    public String getStatus() {
        return status;
    }

    public boolean isCachedAudit() {
        return cachedAudit;
    }

    public String getSummary() {
        return summary;
    }

    public List<SecurityFinding> getFindings() {
        return findings;
    }

    public List<SuppressedFinding> getSuppressedFindings() {
        return suppressedFindings;
    }

    public int getSuppressedCount() {
        return suppressedFindings.size();
    }

    public List<UnifiedDiffPatch> getPatches() {
        return patches;
    }
}
